from enum import Enum


class MatchEventType(str, Enum):
    GOAL = "GOAL"
    ASSIST = "ASSIST"
    GREEN_CARD = "GREEN_CARD"
    YELLOW_CARD = "YELLOW_CARD"
    RED_CARD = "RED_CARD"
    PENALTY_CORNER = "PENALTY_CORNER"
    PENALTY_STROKE = "PENALTY_STROKE"
    SAVE = "SAVE"
    SUBSTITUTION_IN = "SUBSTITUTION_IN"
    SUBSTITUTION_OUT = "SUBSTITUTION_OUT"
    INJURY = "INJURY"